//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MandarinQuest
{


    public partial class ClassSessions
    {

        /// <summary>
        /// gvSessions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvSessions;

    }
}